### ISSUE TITLE
What is the best plase for subscription

### ISSUE THREAD

**Issue by gogainda** [arkency/rails_event_store#10]
I have a order model, in which I want to add event publishing on create callback. Should I add subscribtion to the same place where event is triggered? See the example below

```
def on_create  
    .... 
    notifiers << Managers::OrderCreatedNotifier.new if order.new?
    
    notifiers.each do |n|
      client.subscribe(n, [event.class.name])
    end

    client.publish_event(event, stream_name)
end
```

**Comment by mpraglowski** [comment]
It depends, in RES subscriptions are held as long as RES instance exists, so you could setup new RES instance in each method and add subscription or you could have a single setup of RES in controller that might be used in all services (or command handlers) triggered by user's action.

BTW https://gitter.im/arkency/rails_event_store might be a better place for discussions like this.
