### ISSUE TITLE
Transaction and create hook problem

### ISSUE THREAD

**Issue by gogainda** [arkency/rails_event_store#11]
I have an observer in which i create an event and subscribe on this event like this
```
class ChangedStateOfOrderObserver < ActiveRecord::Observer
  observe :order

  def after_save(order)
    if order.state_changed?
      publish_changed_state_event(order)
    end
  end

  def publish_changed_state_event(order)
    client = RailsEventStore::Client.new
    stream_name = "order_#{order.id}"
    event_data = {
        data: { order_id: order.id, state: order.state }
    }
    event = Orders::StateChanged.new(event_data)

    notifiers = []

    notifiers << Managers::OrderAcceptedNotifier.new if order.accepted?
    notifiers << Managers::OrderCreatedNotifier.new if order.new?
    notifiers << Clients::OrderStateChangedNotifier.new

    notifiers.each do |n|
      client.subscribe(n, [event.class.name])
    end

    client.publish_event(event, stream_name)
  end
end
```
Clients::OrderStateChangedNotifier.new - in this class I send push notification to clients to inform that order's state has been changed.
I run into bug, when if push notificatin can not be performed due to some ssl bugs, order' save function rolls back and app crashes.

What do you think, is it correct behavior that save is rollbacked? I think problem with notifications should not interfere with default work flow of programm, how can I fix it?

**Comment by mpraglowski** [comment]
The assumption behind RES was that (at least for now) all persistence will be done in the same transaction as AR models use. You could prevent that by publishing an event in after_commit instead after_save (in after_commit transaction is already committed and your data is saved). But remember about error handling - if anything goes wrong in after_commit it is up to you to handle that.

And again let's use https://gitter.im/arkency/rails_event_store to discuss things ;)
