### ISSUE TITLE
[FAQ] rails_event_store vs rails_disco gem

### ISSUE THREAD

**Issue by kirantpatil** [arkency/rails_event_store#15]
Hi,

I would like to know both pros and cons of each gem.

https://github.com/arkency/rails_event_store and https://github.com/hicknhack-software/rails-disco.

Thanks.

**Comment by arBmind** [comment]
You should make yourself familiar with both if you want to take an informed decision.

Please share your findings with us.

Thanks.

**Comment by kirantpatil** [comment]
Sticking with rails event store since it is well maintained.
