### ISSUE TITLE
Using Event Store instead of db

### ISSUE THREAD

**Issue by frankieleef** [arkency/rails_event_store#24]
Is it possible to use Greg's Event Store instead of the db? As far as I can see it's mandatory to migrate the database provided.

**Comment by mpraglowski** [comment]
you should use https://github.com/arkency/http_eventstore to connect to Greg's ES

I have am idea to make it a kind of repository in RES someday, but not yet ready for it.

**Comment by frankieleef** [comment]
I know about the http_eventstore gem, but it's only a Http connector, correct? If I want to be able to create, publish and handle events I need to use this gem and it will always write the event to the database as well. Please correct me if I'm wrong

**Comment by mpraglowski** [comment]
> it's only a Http connector, correct

Correct, however the Greg's EventStore does the work here ;)

The `append_to_stream` in that case works like publish_event in RES, Greg's ES (GES) should handle publication of the event to all subscribers. The `http_eventstore` also allows you to build subscribers (simple ones) with `read_events_forward` and long pooling (persistent subscriptions are not yet supported).

**Comment by frankieleef** [comment]
Thanks for the info! I might create a pull request and add this repository, if I find any time for it.

I have another question though. What is needed to subscribe to events? I'm passing in the following:
`Events::DomainEvent.instance.subscribe(test, ['UserCreated'])`

But this don't seem to work. Then I tried the following.

`Events::DomainEvent.instance.subscribe(test, ['::Domain::Events::Users::UserCreated'])`

Again no success..

**Comment by mpraglowski** [comment]
> if I find any time for it.

Yeah, free time :) Also looking for some ;)


> What is needed to subscribe to events? 

Have you tried?

```ruby
Events::DomainEvent.instance.subscribe(test, ['Domain::Events::Users::UserCreated'])
```

That PR https://github.com/arkency/ruby_event_store/pull/8 might be interesting to you.

**Comment by mpraglowski** [comment]
@frankieleef still having issues ? need some help ?
