### ISSUE TITLE
Global configuration leads to unexpected behaviour

### ISSUE THREAD

**Issue by mlomnicki** [arkency/rails_event_store#29]
RES version: current master

```ruby
es1 = RailsEventStore::Client.new
es2 = RailsEventStore::Client.new

class Handler
 def handle_event(event)
   puts "handler fired..."
 end
end

OrderExpired = Class.new(RailsEventStore::Event)

es1.subscribe(Handler.new, [OrderExpired])
es2.publish_event(OrderExpired.new)

# => handler fired...
```
Would you expect that the Handler is being fired? It is, because both `es1` and `es2` share the same
instance of `PubSub::Broker`. This leads to bizzare failures. You instantiate a new RES instance in every test but subscribed handlers are retained.

The problem is due to [this line](https://github.com/arkency/rails_event_store/blob/315a385189d347f16a2c5c132263b0fe384e2298/lib/rails_event_store/client.rb#L5) which is needed for global configuration [here](https://github.com/arkency/rails_event_store/blob/315a385189d347f16a2c5c132263b0fe384e2298/lib/rails_event_store/configuration.rb#L7)

Proposed solution: drop global configuration :smile:

**Comment by gottfrois** [comment]
global subscriber is super useful to broadcast all events into something more async, like a rabbitmq broker

**Comment by gottfrois** [comment]
We should be able to attach instance subscribers to the client instance and not globaly though, sounds like a bug

**Comment by gottfrois** [comment]
Yes `subscribe_to_all_events` is what I use currently

**Comment by mpraglowski** [comment]
> Proposed solution: drop global configuration 

@mlomnicki heh not the best configuration, drop is one of the option, another might be use classes instead of instances (but dropping might be better).

> You instantiate a new RES instance in every test but subscribed handlers are retained.

We really need better tests in RES - maybe it is time to try again mutation testing?

**Comment by mlomnicki** [comment]
Generally, I don't see much value in global configuration. For example, if someone really needs to share configuration, he can wrap RES into a builder. For example:

```ruby
class MyRESBuilder
  def self.build(broker: MyBroker.new, repository: GregsEventsStore.new)
    RailsEventStore::Client.new(broker: broker, repository: repository)
  end
end

es1 = MyRESBuilder.build
es2 = MyRESBuilder.build(repository: InMemoryRepo.new)
```

I find this approach more easier to understand than the `RES.configure` block.
Anyway, global configuration is in Rails' DNA so maybe RES should be a good citizien of the Rails World and provide some globals ;)

> maybe it is time to try again mutation testing?

+1
I'm curious to know if Mutant would have found this issue

**Comment by mpraglowski** [comment]
> RES should be a good citizien of the Rails World and provide some globals ;)

That was an intention here - make a simple solution for Event Sourcing to use with Rails - just add gem and enjoy.

> I'm curious to know if Mutant would have found this issue

Check here https://github.com/arkency/rails_event_store/pull/30 :)

**Comment by mlomnicki** [comment]
> make a simple solution for Event Sourcing to use with Rails

Yeah I thought that's the goal :)

I guess that configuration is not the biggest issue. I would rather expect questions such as _how do I use RES in my controllers/models?_

And to address these questions we could add this line to the README

> Want to use RailsEventStore in your controllers? Just put this line in config/initializers/rails_event_store.rb:

```ruby
RES = RailsEventStore.new
```

...and enjoy!

```ruby
class UsersController < AplicationController
  def create
    user = User.create(params[:user])
    RES.publish(UserCreated.new(name: user.name))
  end
end
```

We could even write a generator that generates `config/initializers/rails_event_store.rb` for you :)

**Comment by mpraglowski** [comment]
> I guess that configuration is not the biggest issue.

Yeah, that's was my lame attempt to make RES more configurable - maybe this is not the correct direction, the users who need custom configuration will know how to do it and how to pass the dependencies via constructor.

**Comment by gottfrois** [comment]
Regarding subscribtions, I would drop the manual configuration and create an interface that would look something like this:

```ruby
class MyConsumer
  include RailsEventStore::Consumer

  consume 'some.event'

  def handle_event(event)
  end
end
```

1. Would get rid of manual configuration
2. Would allow to execute consumers inline or through a broker (RES)
3. Would not get rid of globals (you still need a global to register consumers)

We could introduce routing key regex matching to allow subscribe to all as `consume '*'`

**Comment by mpraglowski** [comment]
Removed in a2d7f589fec50e8cccd0c609e3ec2251cb7587e9

Waiting for your PRs ;)
