### ISSUE TITLE
Add license field to gemspec

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [arkency/rails_event_store#36]
It would facilitate identifying the license using rubygems.org (https://rubygems.org/gems/rails_event_store) and tools like license_finder, if the license field was added to the gemspec.

It seems to be LGPLv3 at the moment, although other related projects like rails_event_store_active_record are MIT. 

Consistent MIT licensing for rails_event_store_active_record, rails_event_store and ruby_event_store would be our preference - but your choice obviously.

**Comment by mpraglowski** [comment]
I will clean the licensing mess soon.

**Comment by mpraglowski** [comment]
Done.

**Comment by andrewdavidmackenzie** [comment]
thanks for both!
