### ISSUE TITLE
apply event method in aggregate should be private

### ISSUE THREAD

**Issue by gottfrois** [arkency/rails_event_store#4]
Any reason why the `apply_events_*` methods are public? From what I understood of aggregate roots, we need to protect their internals from the outside world.

We should probably use `send` here and declare our `apply` methods private. What do you think?

https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/aggregate_root.rb#L19

**Comment by mpraglowski** [comment]
You are right that those methods should be private. The thins is I do not like the current implementation that use send to call methods. Still looking for a better solution. Nevertheless your idea is worth checking - maybe a PR ? ;)

**Comment by gottfrois** [comment]
Sure I can do that but maybe it's not necessary as long as you don't have a clear idea in mind on how you want to do that :)

I'm not sure about that `underscore` method defined in `StringUtils` as well. I don't see a good reason to re-invent the wheel here. We should probably use activesupport here since the gem is supposed to be used on rails projects anyway.

**Comment by mpraglowski** [comment]
Any ideas will be welcomed ;) (especially as PRs :) )

Agree with use of ActiveSupport - this is RailsEventStore - there is no point to avoid Rails dependencies :) Will you prepare PR ?
