### ISSUE TITLE
Update documentation in a gitbook

### ISSUE THREAD

**Issue by Killavus** [arkency/rails_event_store#40]
Right now docs are a little outdated I suppose:

* Still showing `handle_event` which is deprecated in favor of `call` (subscription part)
* Lack of dynamic subscriptions

I think it's necessary to keep docs up to date. I leave this issue as-is, so maybe someone who has a little time can make a PR for it.

**Comment by mpraglowski** [comment]
Also new request metadata feature (Rails request details in event metadata. #39) need to be documented.
