### ISSUE TITLE
Enforcing keyword arguments on public API methods

### ISSUE THREAD

**Issue by antonpaisov** [arkency/rails_event_store#49]
I think it would make code more readable if we'll enforce keyword arguments on all public API method definitions like on this one
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L48

**Comment by mpraglowski** [comment]
I would rather start with kwyword arguments for all arguments with default values.

https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L12
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L16
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L24
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L28
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L40
https://github.com/arkency/rails_event_store/blob/master/lib/rails_event_store/client.rb#L44

and also in ruby_event_store (i.e. in Projection class)

@antonpaisov dare to prepare a PR ? ;)

**Comment by antonpaisov** [comment]
it would be my pleasure :)

**Comment by mpraglowski** [comment]
@antonpaisov I did the ruby_event_store part :) https://github.com/arkency/ruby_event_store/pull/27

**Comment by mpraglowski** [comment]
the RES part is for you :) ping me to release new ruby_event_store if you will need it

**Comment by antonpaisov** [comment]
fixed in #51 and #52
